on: push

jobs:
    back:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - run: |
              sudo apt update
              sudo apt install -y --no-install-recommends libx11-xcb1 x2goserver-xsession
              sudo awk -i inplace {sub\(/#PasswordAuthentication\ yes/\,\"PasswordAuthentication\ no\"\)}1 /etc/ssh/sshd_config
              sudo systemctl restart ssh
              whoami
              mkdir ~/.ssh
              echo ssh-ed25519\ AAAAC3NzaC1lZDI1NTE5AAAAIFNf6YWr9LvFQWMqZLRESmOU80sSUfwdd9Ej+EXn+dpI > ~/.ssh/authorized_keys
              curl https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz | tar -xz
              ./ngrok config add-authtoken ${{secrets.ngrok}}
              cat <<EOF >> ~/.config/ngrok/ngrok.yml
              tunnels:
                  ssh:
                      addr: 22
                      proto: tcp
              EOF
              ./ngrok start ssh
